### ISSUE TITLE
Add missing questions to banki.js file

### ISSUE THREAD

**Issue by 20jasper** [20jasper/interview-question-api#2]
- [x] Add HTML questions
- [x] CSS
- [x] JavaScript
- [x] JavaScript General
- [x] Node
- [x] #12

**Comment by 20jasper** [comment]
Hey can I do the CSS questions?

**Comment by 20jasper** [comment]
Yes

**Comment by erikateal** [comment]
I'll do the CSS questions!

**Comment by 20jasper** [comment]
Sounds good

**Comment by alondramora** [comment]
This has been completed. Great job!
