### ISSUE TITLE
Fix question overflowing div on mobile

### ISSUE THREAD

**Issue by bytesbybianca** [20jasper/interview-question-api#25]
Media query for mobile:
- [ ] Remove dotted border
- [x] Increase width of question div
- [x] Reduce font size

<img src="https://user-images.githubusercontent.com/101486635/170891924-81ff8609-78bc-4b28-b44f-71d893107c47.png" width="45%"> <img src="https://user-images.githubusercontent.com/101486635/170891935-be4c5097-6175-4dd7-bed2-ea235ebc87d7.png" width="45%">

**Comment by 20jasper** [comment]
I fixed this in PR #32
